### ISSUE TITLE
Replace POST with PATCH

### ISSUE THREAD

**Issue by whatyouhide** [Jcambass/toxiproxy_ex#20]
Thanks for the library! 💟 

Seems like some of the `POST` methods on toxiproxy have been turned into `PATCH`es. I get this from the toxiproxy logs when using ToxiproxyEx:

```
ProxyUpdate: HTTP method POST is depercated. Use HTTP PATCH instead.
```

We might not be able to just replace the `POST`s with `PATCH`es, and might have to do so conditionally based on the toxiproxy version.

**Comment by Jcambass** [comment]
Thanks for raising this. I'll check the behaviour of using `PATCH` with older Toxiproxy versions and will move forward with your suggestion accordingly.

**Comment by whatyouhide** [comment]
I think we might want to use POST for  a while more and then drop support for older Toxiproxy versions that don't support PATCH. 🙃

**Comment by Jcambass** [comment]
Yeah that seems fair. Looking at the official go client, I can see [that they still use `post` and will switch to `patch` once they publish V3 of Toxiproxy itself](https://github.com/Shopify/toxiproxy/blob/3399ea0235ca3961e30ed9cb3a0ad52ddc8398c3/client/proxy.go#L36-L39).

The official ruby clients [does also still use `post` and has no code path for `patch` yet](https://github.com/search?q=repo%3AShopify%2Ftoxiproxy-ruby+Net%3A%3AHTTP&type=code).

So I think it's best to document that this lib is for Toxiproxy V2.X and wait with changing this until Toxiproxy V3.0 is released.

**Comment by Jcambass** [comment]
Hi @whatyouhide 👋 Not really, I only need to publish a new release and create the changelog. Unfortunately It's been kinda hard to find the time over the last months. But be assured it's still on my list. Also disclaimer, I'm not using this library myself anymore, so in case you want to fork and maintain it or even just take over partial maintainership of what's in this repo let me know!

**Comment by Jcambass** [comment]
@whatyouhide I just published [2.0.0](https://hex.pm/packages/toxiproxy_ex/2.0.0) now. I'd like to keep this issue open until Toxiproxy 3.0 drops OR all the official clients change to using `PATCH` at which point I'll make the change and close this issue.

**Comment by whatyouhide** [comment]
> Also disclaimer, I'm not using this library myself anymore, so in case you want to fork and maintain it or even just take over partial maintainership of what's in this repo let me know!

@Jcambass this lib works great so I see no reason for forking, yeah. I can take over partial maintainership though if it's something that could help you. I use this lib in a couple of OSS projects (Redix and Xandra) so I’m definitely an active user 🙃

**Comment by whatyouhide** [comment]
Hey @Jcambass if you ever want me to help out, I'd be happy too. For now I'll close this issue as I’m trying to clean up my active working surface 🙃
