### ISSUE TITLE
Test case failed due to different Toxiproxy installed

### ISSUE THREAD

**Issue by kianmeng** [Jcambass/toxiproxy_ex#3]
Different user may install different Toxiproxy version.

```
  1) doctest ToxiproxyEx.version!/0 (19) (ToxiproxyExTest)
     test/toxiproxy_ex_test.exs:3
     Doctest failed
     doctest:
       iex> ToxiproxyEx.version!()
       "2.1.2"
     code:  ToxiproxyEx.version!() === "2.1.2"
     left:  "2.1.4"
     right: "2.1.2"
     stacktrace:
       lib/toxiproxy_ex.ex:436: ToxiproxyEx (module)
```

**Comment by Jcambass** [comment]
Thanks for bringing this up.

I'm actually aware of this but really wanted to have a doctest for this. I think it's probably worth keeping the example but in a way where it isn't treated as a doctest and therefore not validated.
